### ISSUE TITLE
Remove react and react-native from dependencies

### ISSUE THREAD

**Issue by draperunner** [harness/ff-react-native-client-sdk#10]
You have listed react and react-native as both dependencies and peerDependencies in package.json. Only peer dependencies should be used, so that consumers don't get conflicting versions of these in their project.

Also, the peer dependencies should use a less restrictive version range. React v17 is out, and 0.67 is the latest react-native. I guess this package should work well with both of them.

**Comment by milos85vasic** [comment]
Done.
