### ISSUE TITLE
Uncaught Error - new NativeEventEmitter() requires a non null argument

### ISSUE THREAD

**Issue by KOKOdeveloper** [harness/ff-react-native-client-sdk#19]
Hello,

I need to use harness for feature flags for react native project, I follow up every step from you documentation and I'm not able to build application because of crash: 
![Screenshot 2023-10-12 at 09 35 52](https://github.com/harness/ff-react-native-client-sdk/assets/39067151/445ac334-91e4-4212-b4f1-ad1b75c0220c)

I tried to debug this and I realise that this line of code is the issue
![Screenshot 2023-10-12 at 09 33 42](https://github.com/harness/ff-react-native-client-sdk/assets/39067151/a3efa01f-bc01-47a1-9166-e2c08a627c84)
At this point it will try to execute new NativeEventEmitter with null
![Screenshot 2023-10-12 at 09 44 00](https://github.com/harness/ff-react-native-client-sdk/assets/39067151/11c54cb8-ef6f-4566-b3f2-c535c32e0ba1)

This is on react-native version 0.72.4

I also tried on older version 0.71.4 but it has the same issue.

Please help me how to solve this error

**Comment by bormm** [comment]
@davejohnston and @erdirowlands 

As the (now) responsible team lead here and a paying customer it a bit frustrating to see how the issue from my team mate was ignored within the last 4 months. Today the question was raised why not switch the feature flag backend to other competitors.

So lets see: There is a deprecation note in your online documentation (now):
![image](https://github.com/harness/ff-react-native-client-sdk/assets/23644239/c9a99d29-ad04-4f5f-875f-84e793706e03)

I expect this ticket will never be solved and it also does not make sense to solve it with that in mind. Anyway I think some feedback in a reasonable time can be expected for next time in such a case.

Also this repository does not contain any deprecation note, so you should add one with a red color. I am no expert in that area, but there is no hint in the react SDK about usage in react native environment. So nothing to mention? Works as perfect replacement for React Native on iOS?

**Comment by davejohnston** [comment]
@bormm let me give you my apologies for this.  We should have been updating you're colleague on the plans for react native.  
As an existing customer please do raise tickets via the customer support portal as they will be routed directly to us and flagged with both the product and engineering team (though that is no excuse for not keeping these issues active).  

We are currently working to provide examples of how to use the react SDK within a reactive native environment.  Can I ask, have you adopted the react native SDK anywhere in existing code, or were you alway blocked from using it?  In either case we can offer some time with one of our engineers to help provide guidance on using the react SDK.

If you would like to discuss how the react SDK can be used, please raise a support ticket (if you don't have access to the support portal let me know here and I will work with CS to reach out to you).

**Comment by knagurski** [comment]
@KOKOdeveloper, @bormm we've just released v2.0.0 of the React Native Client SDK that simplifies how to install and use the SDK in React Native. I'm going to close this issue now. Please reach out if there is anything we can help with!
